Fix "arg" dependency for package
The published package command uses "arg", so it should be in the dependencies.

Error example:
```
~/ghq/github.com/tash-2s/rmrk-batch-samples main % yarn rmrk-tools-consolidate
yarn run v1.22.10
$ /Users/t/ghq/github.com/tash-2s/rmrk-batch-samples/node_modules/.bin/rmrk-tools-consolidate
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'arg'
Require stack:
- /Users/t/ghq/github.com/tash-2s/rmrk-batch-samples/node_modules/rmrk-tools/dist-cli/cli/consolidate.js
```

The issue was introduced in this PR. https://github.com/rmrk-team/rmrk-tools/pull/31